
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBbszxNRri_Lr_6d9cmm0yTamOSfKJawo',
    appId: '1:913969877080:web:bd35786e707d7065defa2d',
    messagingSenderId: '913969877080',
    projectId: 'afercon-lda-24cac',
    authDomain: 'afercon-lda-24cac.firebaseapp.com',
    storageBucket: 'afercon-lda-24cac.appspot.com',
    measurementId: 'G-0BY1M8GY39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8SQ2nGgBhQYrGi7nFkmizwZ3hGKFISbA',
    appId: '1:913969877080:android:b028151511ae469cdefa2d',
    messagingSenderId: '913969877080',
    projectId: 'afercon-lda-24cac',
    storageBucket: 'afercon-lda-24cac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbszxNRri_Lr_6d9cmm0yTamOSfKJawo',
    appId: '1:913969877080:ios:MANUAL_CONFIG_NEEDED',
    messagingSenderId: '913969877080',
    projectId: 'afercon-lda-24cac',
    storageBucket: 'afercon-lda-24cac.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
